import { NextRequest, NextResponse } from "next/server";

// Eduland-style mock report data
const mockReports = [
  {
    id: 1,
    name: "ONYINYECHUKWU MARY NWODO",
    class: "YEAR 1",
    term: "SECOND",
    timeSchoolOpened: 60,
    timePresent: 60,
    session: "2024/2025",
    subjects: [
      {
        name: "Numeracy",
        hw: 20,
        cw: 13,
        test: 20,
        total: 53,
        grade: "B",
        teacher: "Mrs Oyeniyi",
      },
      {
        name: "Literacy",
        hw: 17,
        cw: 20,
        test: 19,
        total: 56,
        grade: "A",
        teacher: "Mrs Oyeniyi",
      },
      {
        name: "Diction",
        hw: 20,
        cw: 20,
        test: 20,
        total: 60,
        grade: "A",
        teacher: "Mr. Henshaw",
      },
      {
        name: "Literature",
        hw: 20,
        cw: 18,
        test: 16,
        total: 54,
        grade: "A",
        teacher: "Mrs Oyeniyi",
      },
      {
        name: "Computer",
        hw: 16,
        cw: 16,
        test: 20,
        total: 52,
        grade: "B",
        teacher: "Mr. Adepoju",
      },
      {
        name: "Vocational Studies",
        hw: 20,
        cw: 16,
        test: 18,
        total: 54,
        grade: "A",
        teacher: "Mrs Oyeniyi",
      },
      {
        name: "Verbal Aptitude",
        hw: 19,
        cw: 19,
        test: 20,
        total: 58,
        grade: "A",
        teacher: "Mrs Oyeniyi",
      },
      {
        name: "Quantitative Reasoning",
        hw: 20,
        cw: 20,
        test: 10,
        total: 50,
        grade: "B",
        teacher: "Mrs Oyeniyi",
      },
      {
        name: "General Studies",
        hw: 20,
        cw: 20,
        test: 20,
        total: 60,
        grade: "A",
        teacher: "Mrs Oyeniyi",
      },
      {
        name: "C.R.S.",
        hw: 20,
        cw: 16,
        test: 17,
        total: 53,
        grade: "B",
        teacher: "Mrs Oyeniyi",
      },
      {
        name: "Fine Arts",
        hw: 15,
        cw: 14,
        test: 14,
        total: 43,
        grade: "C",
        teacher: "Mr Emmanuel",
      },
      {
        name: "French",
        hw: 20,
        cw: 20,
        test: 16,
        total: 56,
        grade: "A",
        teacher: "Ms. Akhideno",
      },
      {
        name: "Yoruba",
        hw: 20,
        cw: 20,
        test: 18,
        total: 58,
        grade: "A",
        teacher: "Mrs Oyeniyi",
      },
      {
        name: "Music",
        hw: 19,
        cw: 19,
        test: 19,
        total: 57,
        grade: "A",
        teacher: "Mr Shina",
      },
      {
        name: "Science",
        hw: 20,
        cw: 14,
        test: 16,
        total: 50,
        grade: "B",
        teacher: "Mrs Oyeniyi",
      },
      {
        name: "History",
        hw: 20,
        cw: 20,
        test: 19,
        total: 59,
        grade: "A",
        teacher: "Mrs Oyeniyi",
      },
    ],
    overall: {
      totalPossible: 960,
      totalScore: 873,
      percentage: 91,
      overallGrade: "A",
    },
    key: [
      { grade: "A", meaning: "Excellent", range: "54-60" },
      { grade: "B", meaning: "Very Good", range: "48-53" },
      { grade: "C", meaning: "Good", range: "42-47" },
      { grade: "D", meaning: "Fairly Good", range: "36-41" },
      { grade: "E", meaning: "Average", range: "30-35" },
      { grade: "F", meaning: "Needs Improvement", range: "24-29" },
      { grade: "Weak", meaning: "Weak", range: "18-23" },
      { grade: "Very Weak", meaning: "Very Weak", range: "Below 18" },
    ],
    generalComment:
      "In all academic disciplines, Onyinyechukwu is improving. However, she would benefit from more regular homework completion to solidify understanding of concepts.",
    effectiveTraits: {
      behaviour: "A",
      punctuality: true,
      mentalAlertness: ["A", "C"],
      respect: true,
      neatness: true,
      politeness: true,
      honesty: true,
      relationshipWithPeers: true,
      willingnessToLearn: true,
      spiritOfTeamwork: true,
      health: true,
    },
    classTeacher: "Mrs Oyeniyi",
    classTeacherSignature: "",
    nextHalfTermBegins: "Monday, 24th February, 2025",
    authorizedSignature: "",
  },
];

export async function GET(request: NextRequest) {
  try {
    return NextResponse.json({
      success: true,
      reports: mockReports,
    });
  } catch (error) {
    console.error("Error fetching student reports:", error);
    return NextResponse.json(
      { message: "Internal server error" },
      { status: 500 }
    );
  }
}
